all:
  children:
    worker:
      hosts:
        worker:
          ansible_host: 192.168.0.20
    webservers:
      hosts:
        wb01:
          ansible_host: 192.168.0.22
        wb02:
          ansible_host: 192.168.0.23
    databases:
      hosts:
        db01:
          ansible_host: 192.168.0.24
    cache:
      hosts:
        cache01:
          ansible_host: 192.168.0.25
    balancer:
      hosts:
        lb01:
          ansible_host: 192.168.0.26
    monitoring:
      hosts:
        monitor:
          ansible_host: 192.168.0.27
